blank_issues_enabled: false
contact_links:
  - name: Report a Security Vulnerability
    url: https://github.com/kalidraco/pickyhack/security/advisories/new
    about: Please report sensitive security vulnerabilities privately through GitHub Security Advisories.
